ZIG=zig
ZFLAGS=cc -O3  
TARGET=yes.zig

all:
	@echo "Build yes..."
	@$(ZIG) $(ZFLAGS) $(TARGET) -o main

global:
	@echo "Build yes..."
	@$(ZIG) $(ZFLAGS) $(TARGET) -o ../../yes.out

clean: 
	@echo "Clean..."
	@rm main 

