CPP=g++
KCFLAGS=-O3 -static 
TARGET=calc.cpp

all:
	@echo "Build calc..."
	@$(CPP) $(TARGET) $(KCFLAGS) -o main.out

global:
	@echo "Build calc..."
	@$(CPP) $(TARGET) $(KCFLAGS) -o ../../calc.out

clean:
	@echo "Clean..."
	@rm main.out


